all: 
	rm -rf *.class 
	javac Main.java
	java Main
help: 
	@echo "Desenvolvido por thiago gomes\n"
	@echo "para executar o programa deste lab, basta digitar make\n"
	@echo "lembre-se de descomentar o exercicio desejado"